# Generated by Django 6.1.1 on 2026-09-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default='Enter here...', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
